import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './components/Header'

export default function Home() {
  return (
    <div className="dark:bg-slate-400 m-0 p-0 top-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />


      <h1 className="w-full text-center my-6 font-bold text-5xl">- WORKS -</h1>
      <div className="flex justify-center mx-4 flex-wrap">
        <Card url="https://ide-python.herokuapp.com/" img="/python-ide.png" title="【NEW!】自作IDE" desc="コードインタビューに備えて競技プログラミングを勉強しています。ネット上にVimが操作できて、Inputを事前に書くことができて、Ctrl+Sで自動で実行してくれるものがなかったので、作りました。" isSite={true} />
        <Card url="https://stars-yeah.herokuapp.com/" img="/stars.png" title="STARS" desc="Three.jsというブラウザ上で3DCGをシミュレーションできるライブラリを試して見ました。" isSite={true} />
        <Card url="https://maketen.herokuapp.com/" img="/maketen.png" title="Make Ten" desc="1,3,3,7を四則演算を利用して10にせよ。そんな広告を電車で見かけ、どんな数字4つの数字に対しても四則演算を利用して10にしてくれるWEBアプリを開発しました。" isSite={true} />
        <Card url="https://keijibnan.herokuapp.com/" img="/keijiban.png" title="掲示板" desc="掲示板のように入力した文字が右から左へ流れるテキストを作りたくなりました。それぞれのアルファベットに対してどの部分を黒に塗るかJSONのデータを作成し、一定時間ごとにスライドするように設計しています。" isSite={true} />
        <Card url="#" img="/charge.png" title="Charge" desc="Javascriptの充電を検知する機能を利用して、充電がされなくなったときにLINE通知をするアプリを作りました。停電を検知するために作成しましたが、ブラウザのバージョンが変わって検知機能が使えなくなってしまいました。" isSite={false} />
      </div>





    </div>
  )
}

function Card(props) {
  return (
    <div className={`max-w-md bg-white rounded-lg border py-0 mt-0  shadow-md dark:bg-gray-800 flex-auto m-3 border-gray-200  dark:border-gray-700"}`}>
      <a href={props.url} className="items-center">
        <img src={props.img} alt="Picture of the author" style={{ height: '250px', objectFit: "fill" }} className="center"
        />
      </a>
      <div className="p-5">
        <a href="#">
          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{props.title}</h5>
        </a>
        <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">{props.desc}</p>
        {props.isSite ? <a href={props.url} className="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
          サイトに移動
          <svg className="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </a> : ""}
      </div>
    </div>

  )
}